---
output: github_document
---

## correspondence 



### 2019-03-10

**RL** You had not yet created the .Renviron file, so I did it for you. Please make sure you create the independent package library as described [here](https://github.com/DSR-RHIT/me447-visualizing-data/blob/master/cm/cm902-software-studio.md#create-the-renviron). This step is important for seamless collaboration. 

**RL** I've revised the prompts for the week 2 reading. Please create your reading response file as described [here](https://github.com/DSR-RHIT/me447-visualizing-data/blob/master/cm/cm902-software-studio.md#setup-reading-response). Remember to complete your responses in writing before class on Tuesday. 
https://github.com/DSR-RHIT/me447-visualizing-data/blob/master/reports/reading-prompts-1.Rmd

**RL** This is an example of a second comment in reverse chronological order. 

**RD** And its response. 



### 2019-02-10

**RL** I will use this Rmd file for corresponding with you about your portfolio. Entries will be dated and listed in reverse chronological order--that is, with the most recent at the top of the page. You should record your responses directly below, for example: 

**RD** This is a sample response to the comment above.
