---
title: "reading-responses"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## week 10 reading prompts  

Spence, Ian (2006) William Playfair and the psychology of graphs. In: *IEEE
Transactions on Professional Communication.* Alexandria, VA: American
Statistical Association, section on statistical graphics, 2426--2436.

<br>
**Prompt:** Explain what the author means by the "psychology of graphs." 

**Response:** 

Graphs have the ability to exploit our natural perception and cognitive challenges. Playfair noticed this and wanted to adapt graphs to improve cognitive ability.

<br>
**Prompt:**  Psychology was identified as its own science in the 1730s and 
experimental psychology research began in the 1830s. Thus William Playfair's 
life (1759--1823) overlapped the beginnings of psychology as a science. But 
he was not a psychologist---he was a craftsman by trade who was exposed to the 
best minds of the Scottish Enlightenment. His experience included engineering, 
commerce, and publishing (as well as dubious investment schemes and attempted 
extortion). Nevertheless, the author makes connections between Playfair and 
psychology. 

Describe those connections.  

**Response:**  
Idea of experimental psychology. Dealing with the preattentive processing and the attention driven aspect of the viewers mind.Dugald Steward and Thomas reid helped form his ideas on perception and memory. His brother made the connection and started plotting numbers.


<br>
**Prompt:** In section 2.3, the author describes 5 examples of graphical 
conventions that Playfair invented or adapted. Discuss your interpretation of 
each convention in light of our other readings and discussions this term. 

**Response:** 
Framing, Titling, Color,labels,time, titling, Slope, Length, Area. It was interesting to see how his interest in art brought him to adding color to the graph. He used cartography as an inspiration to add grids to the graph.




##week 8 reading prompt

Kostelnick, Charles (2007) The visual rhetoric of data displays: The conundrum
of clarity. *IEEE Transactions on Professional Communication* 50(2): 280--294.

**Prompt:** 
Different facets of the graph  ? 
**Response:** 
Too little or too much on the graph. ethos logos pathos kairos. Need to include the pathos as well.
Rhetoric of science:- 


**Prompt:** 
How does the author describe other communities?
**Response:**
Members of a community rarely care about different ideas from other communities. It is important to know if where they belong changes the way you look at things.


**Prompt:**
Rhetoric of participation?

**Response:** 
Making things interactive and giving the audience an option to see what they want. accept different readers find different things credible.

**Prompt:**
Rhetoric of adaptation?

**Response:** 
Change context and complexity of the graph based on technical knowledge of the audience. Expert vs layman


**Prompt:**
Rhetoric of science?

**Response:** 
Misconception: there is only 1 truth and people should see that.



**Prompt:**
Social Rhetoric?

**Response:** 
What is all the baggage the the audience brings with them. All of the preconceptions with the audience      

##week 6 reading prompt
Dragga, Sam & Dan Voss (2001) Cruel pies: The inhumanity of technical
illustrations. *Technical Communication* 48(3): 265--274.

**Prompt:** Explain how the prevalent treatment of ethics in visual communication is lacking.

**Response:** 
So far wherever the issus of misguidance has been brought up, it has been related to accuracy and validity. Most of the books that cover ethics in visualization usually only talk about graph distortion and honesty instead of deception. This ends up being not enough.


**Prompt:** Explain the purpose of "humanizing" data displays depicting human suffering or death. 

**Response:**  
By omitting the human misery caused by that militarycampaign,  the  illustration  could  be  said  to  constitute  adistortion  of  the  reality  that  escapes  the  statistics.  Thegraphic isn’t so much deceptive, however, as it is plainlyinhumane—insensitive or indifferent to the human condi-tion it depicts. It is a graphic that exhibits the “ethic ofexpediency” (Katz 1992).

By humanizing the data we are making sure that we are not omitting the human misery. If we do then the figure is distorted of its reality. When we do not see the people we do not see the suffering so it is difficult to understand the gravity of the situation.


**Prompt:**  Consider the authors' attempts at redesigning such data displays. Did one in particular strike you as ineffective? Explain    

**Response:** 

I feel the cold statistics did not do the best job at humanizing. Here I feel it was not important to add a picture since cold is not severe enough for us to humanize it. The cold picture is also misleading since it is not clear what the person in bed is doing and if it requires explaining, not worth it.


**Prompt:**  Did one in particular strike you as effective? Explain. 


**Response:** 
The babies graph was effective since just a plain histograph is insensitive towards falling babies and does not show the gravity of the situation.
The one with the woodcutter was also misleading.









##week 4 reading prompt

Wainer, Howard (2014) Fifteen displays about one thing. In: *Medical
illuminations: Using evidence, visualization, and statistical thinking to
improve healthcare.* UK: Oxford University Press, 32--49.

Definition: "Gram staining" (named after its inventor, the Danish scientist 
Hans Christian Gram) is a method of staining to distinguish one type of 
bacterium from another---it can be used as a faster substitute for culturing. 
Gram staining is a category with two levels: some bacteria are Gram stain 
negative and some are Gram stain positive. Read more about it on the  
[Gram stain Wiki](https://en.wikipedia.org/wiki/Gram_stain).  



**Prompt:** Reviewing the article carefully, come up with a list of variables. 
Classify each as quantitative or categorical, and if categorical, the levels. 

**Response:** 


Antibiotic Type , categorical, 3
Bacteria Type, category, 16

Minimum Concentration, quant
Gram positive/negative,category,2


**Prompt:** The article title is "Fifteen displays about one thing." After 
reading the entire article, what is the "one thing?" Note that the "one thing" 
might imply multiple goals or more than one question. 

**Response:** 
Main goal - identify which drug and conc is best for certain bacteria.
Secondary goal - best drug for specific bacteria class.




**Prompt:** In your opinion, which of the 15 displays best answers the 
question(s) about the "one thing?"

**Response:**  Figure 2.19


**Prompt:** Explain why.  

**Response:**
2.14 - can't tell the difference between positive and negative bacteria

2.17 - lacks specificity and is hard to read.

All these problems are not there in 2.19



**Prompt:** Re-read Wainer's conclusion section. What main points does he make 
about graph design or visual rhetoric that you could apply to your own work 
this term. 

**Response:** Using data visualizations for evidence is useless without having a 
question you want to answer in mind. It is important to think about what you are trying to show rather than just doing something and end up showing a misleading graph. 



## week 2 reading prompts  



**Prompt:** Tufte says, "Regardless of the indirect cultural causes of the
accident, there was a clear proximate cause." Summarize Tufte's explanation 
of the proximate cause.  

**Response:** 
While everone was looking at the problem from different angles, Tufte claims the main reason for the failure was the inability to assess the link between link temperatures and O ring damage. He states this with the help of many graphs that were shown before the day of the launch. One of the charts lacked the names of the authors of the chart that might cause lack in credibility. One of them talks about the same rocket with 3 different names which can lead to confusion and issues like these that fail to capture the relationship with temperature.

**Prompt:** Describe the evidence the author presents to support those ideas.

**Response:**  
The first chart does not have names which takes out the possibility of communication and credibility check with the authors. The second chart talks about Oring damage but the chart does not say anything about the cause of the damage (temp). It also has 3 different names for the same rocket so it causes confusion among readers. Another chart talsk about the relationship between erosion of primary ring and secondary ring. it was odd that even this graph the temp is not mentioned although other visual representation is covered.

**Prompt:** What data were used in making the decision to launch? What data 
were not used but should have been used (according to Tufte) in making the
launch decision?

**Response:** 
They only used a small subset of the available data.
Any data that tried to determine the realtionship with temperature was not used. Even the temp charts for DM, Qm, launches with blowby and challenger were missing about 92% of the temperature data.


**Prompt:** On page 23, Tufte presents a graph that provides visual evidence
that the "launch was completely outside the engineering database accumulated 
in 24 previous flight." Describe the structure of this data set:

- Number of observations 
- Data structure: classify each variable as quantitative (continuous or discrete) and categorical (nominal or ordinal and number of levels). 

**Response:**  
It is a data matrix with history of temperature and O ring damage.
no of observations - 23
Oring damage index - quant (discrete)
Temp - quant (continuous)

**Prompt:** Summarize the main thesis of the paper.  

**Response:** 
The purpose of this paper is to look give a statistical explanation to what went wrong. Essentially Tufte said that visual representaions (since they can be so powerful) should be governed by principles of reasoning about quantitative evidence. We can see witht this case study that just clearly representing things and labelling can help a first time looker of the graph to know what is missing. He puts forward the following principles:
- documenting
-enforcing appropriate comparisons
-demonstrating cause and effect
-expressing quantitatively
- realizing multivariate nature of analytical problems
- inspecting alternate explanations.

If we try to adhere to this we can explore the data well enough to not mislead ourselves and the audience.

[Reading response 1](reports/reading-response-1-Tufte-1997.md) Edward Tufte (1997) The decision to launch the space shuttle Challenger.    
