---
title: "R Notebook"
output: github_notebook
---

```{r}
library(ggplot2)
library(dplyr)
library(scales)
library(DT)
library(scales)
library(lubridate)
```

```{r}
killed  <- read.csv("../data-raw/cpj.csv", na.strings=c("","NA"))
```



```{r}
killed$Date <- as.Date(killed$Date, format = "%B %d, %Y")
killed$Month <- factor(month(killed$Date, label = TRUE))
killed$Day <- factor(day(killed$Date))
killed$Year <- factor(year(killed$Date))
killed$WeekDay <- factor(wday(killed$Date, label = TRUE))
```


```{r}
dim(killed)
```


```{r}
killed <- killed %>%
        as_tibble() %>%
        glimpse()
```


```{r}
p <- ggplot(killed[!killed$Year %in% c(3, 14,30, NA) & !is.na(killed$Type_death), ], aes(Year, fill = Type_death)) + 
            geom_bar() +
                    labs(x = "Year", 
                             y = "Death Toll",
                             title = "Journalists killings by Year and Type", 
                              
                             caption = "Source: Kaggle"
                    ) +
                    theme(legend.position = "bottom")
```

```{r}
p
```

```{r}
ggsave(filename = "journalist-deaths.png",
        path    = "../figures/",
        width   = 16,
        height  = 8,
        units   = "in",
        dpi     = 300)
```
