---
title: "d4-design"
output: github_notebook
---

```{r}
library(ggplot2)
library(dplyr)
library(scales)
library(DT)
library(scales)
library(lubridate)
```





```{r}
tempKilled <- readRDS("../data/journalists.rds") %>% 
        glimpse()
```


```{r}
p <- ggplot(tempKilled, aes(Year, fill = Type_death)) + 
            geom_bar() +
        
                    labs(x = "Year", 
                             y = "Death Toll",
                             title = "Journalists killings by Year and Type", 
                             subtitle = "Total :1168",
                              fill= "Reason for Death",
                             caption = "Source: Kaggle"
                    ) +
                    theme(legend.position = "bottom")
        
```

```{r}
p
```


```{r}
ggsave(filename = "journalist-death.png",
        path    = "../../../Desktop/School/Senior/Data Visualization/ME447-singhab/figures",
        device  = "png",
        width   = 16,
        height  = 8,
        units   = "in",
        dpi     = 300) 
```
