---
title: "R Notebook"
output: github_notebook
---

```{r}
library(tidyverse)
library(graphclassmate)
library("GGally")
library("scagnostics")
library("gghighlight")
library(ggplot2)
```


```{r}
fifa_my <- readRDS("../data/fifa-d6.rds") %>% 
        glimpse()
```



```{r}
p<- ggparcoord(data = fifa_my, columns = 8:15, groupColumn  = "Position",
           scale        = "globalminmax", 
           # scaleSummary = "median", # use with  scale == “center”
           # centerObsID  = 1,        # use with scale == “centerObs”
        
           missing      = "exclude", 
           order        = "Skewed", # scagnostic measures 
           alphaLines   = 0.4, 
           mapping      = NULL, 
           title        = "Comparison of Physical attributes based on Position") +
  labs(x = "Attributes", y = "Rating")
```
```{r}
p
```





```{r}
ggsave(filename = "d6-multiFifa.png",
        path    = "../figures/",
        width   = 8,
        height  = 6,
        units   = "in",
        dpi     = 400)
```




